/*
BRONZE LAYER ORCHESTRATION:
  Automate the Bronze load using S3 Directory Streams and Tasks.
  Ensures data is loaded only when changes are detected in S3.

WARNING:
  Tasks must be RESUMED manually after modification or deployment.

REQUIREMENTS:
  ROLE: ACCOUNTADMIN, WH: COMPUTE_WH, DB: DATA_WAREHOUSE, SCHEMA: BRONZE
*/

USE ROLE ACCOUNTADMIN;
USE DATABASE DATA_WAREHOUSE;
USE SCHEMA BRONZE;

-- 1. Ensure Directory Table is enabled for the Stage
-- Using ALTER instead of CREATE OR REPLACE to avoid breaking existing streams.
ALTER STAGE DATA_WAREHOUSE.BRONZE.BRONZE_STAGE SET DIRECTORY = (ENABLE = TRUE);

-- 2. Create or Recreate the Stream
-- If you ever see "Base stage dropped", running this script will fix it.
CREATE OR REPLACE STREAM DATA_WAREHOUSE.BRONZE.BRONZE_STAGE_STREAM
    ON STAGE DATA_WAREHOUSE.BRONZE.BRONZE_STAGE;

-- 3. Primary Task: Simply syncs S3 metadata every minute
CREATE OR REPLACE TASK DATA_WAREHOUSE.BRONZE.TSK_SYNC_S3_META
    WAREHOUSE = COMPUTE_WH
    SCHEDULE = '1 MINUTE'
AS
    ALTER STAGE DATA_WAREHOUSE.BRONZE.BRONZE_STAGE REFRESH;

-- 4. Secondary Task: Only runs IF the Stream detects changes (new/replaced files)
CREATE OR REPLACE TASK DATA_WAREHOUSE.BRONZE.TSK_LOAD_BRONZE
    WAREHOUSE = COMPUTE_WH
    AFTER DATA_WAREHOUSE.BRONZE.TSK_SYNC_S3_META
    WHEN SYSTEM$STREAM_HAS_DATA('DATA_WAREHOUSE.BRONZE.BRONZE_STAGE_STREAM')
AS
    CALL DATA_WAREHOUSE.BRONZE.SP_LOAD_BRONZE();

-- 5. Resume tasks (Child first)
ALTER TASK DATA_WAREHOUSE.BRONZE.TSK_LOAD_BRONZE RESUME;
ALTER TASK DATA_WAREHOUSE.BRONZE.TSK_SYNC_S3_META RESUME;