/*
INIT DATABASE:
  Setup Medallion Architecture (Bronze -> Silver -> Gold)

WARNING:
  'CREATE OR REPLACE' will drop all existing data.

REQUIREMENTS:
  ROLE: ACCOUNTADMIN, WH: COMPUTE_WH
*/
USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;
CREATE OR REPLACE DATABASE DATA_WAREHOUSE;
USE DATA_WAREHOUSE;
CREATE OR REPLACE SCHEMA BRONZE;
CREATE OR REPLACE SCHEMA SILVER;
CREATE OR REPLACE SCHEMA GOLD;